// Shared typography and spacing tokens for the HTML and PDF renderers (points).
export const DOCUMENT_STYLES = {
  modern: {
    align: "center",
    accent: "#345b91",
    nameSize: 23,
    nameBold: true,
    uppercase: true,
    rule: 0.6,
    headerRule: 0,
    sectionGap: 6,
    entryGap: 3,
    lineGap: -1.5,
  },
  minimal: {
    align: "left",
    accent: "#242424",
    nameSize: 25,
    nameBold: false,
    uppercase: false,
    rule: 0.3,
    headerRule: 0,
    sectionGap: 12,
    entryGap: 7,
    lineGap: 0.4,
  },
  corporate: {
    align: "left",
    accent: "#172033",
    nameSize: 25,
    nameBold: true,
    uppercase: true,
    rule: 1.4,
    headerRule: 2,
    sectionGap: 8,
    entryGap: 4,
    lineGap: -0.7,
  },
};
